management:
  endpoints:
    web:
      base-path: "/"
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: false
server:
  port: 3001


spring:
  databaseUrl: 'postgres://postgres:postgres@localhost:5432/payments_db?sslmode=disable'

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true

redis:
  url: 'redis://localhost'

cloud:
  aws:
    credentials:
      access-key: local
      secret-key: local
    sqs:
      endpoint: 'http://localhost:4566'
      paymentRequestQueueName: 'payment-request-queue.fifo'
      paymentRequestDlqQueueName: 'payment-request-queue-deadletter.fifo'

platform:
  url: 'http://localhost:3001'
